services:
  api:
    image: robertkilduff/rocket-app:latest
    build:
      context: .
    environment:
      SECRET_KEY: ${SECRET_KEY}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    ports:
      - "8000:8000"
    volumes:
      - ./database.sqlite:/rocket-app/database.sqlite
      - ./migrations:/rocket-app/migrations

x-bake:
  targets:
    api:
      context: .
      dockerfile: Dockerfile
      args:
        SECRET_KEY: ${SECRET_KEY}
        JWT_SECRET_KEY: ${JWT_SECRET_KEY}
