version: '3'
services:
  api:
    image: your-docker-username/your-image-name:latest
    environment:
      SECRET_KEY: ${SECRET_KEY}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    ports:
      - "8000:8000"
    volumes:
      - ./database.sqlite:/rocket-app/database.sqlite
      - ./migrations:/rocket-app/migrations

