version: '3'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=/rocket-app/database.sqlite
    volumes:
      - ./database.sqlite:/rocket-app/database.sqlite
      - ./migrations:/rocket-app/migrations
      - ./Rocket.toml:/rocket-app/Rocket.toml
      - ./.env:/rocket-app/.env